# Overview
Numpy is a first-rate library for numerical programming
- Widely used in academia, finance and industry.
- Mature, fast, stable and under continuous development.

Numpy arrays / fundamental array processing operations 
    
    
### Introduction to Numpy([Numpy Documentation](https://numpy.org/doc/stable/))

The essential problem that NumPy solves is fast array processing.

For example, suppose we want to create an array of 1 million random draws from a uniform distribution and compute the mean.

If we did this in pure Python it would be orders of magnitude slower than C or Fortran.

This is because

Loops in Python over Python data types like lists carry significant overhead.
C and Fortran code contains a lot of type information that can be used for optimization.
Various optimizations can be carried out during compilation when the compiler sees the instructions as a whole.
However, for a task like the one described above, there’s no need to switch back to C or Fortran.    
    



- (Note) Attribute, Method
    - Attribute : class.attribute
        - A variable stored in an instance or class is called an attribute.
    - Method : class.method()
        - A function stored in an instance or class is called an method.

In [1]:
import numpy as np
from numpy import random
import time

start = time.time()
x = random.uniform(0, 1, size=10000000)
print(x.mean())
end = time.time()
end-start

0.4998956493356929


0.10103845596313477

### (1) Numpy arrays

The most important thing that Numpy defines is an array data type formally called a Numpy.ndarray.

Numpy arrays power a large proportion of the scientific Python ecosystem.

(1) Creating arrays

In [2]:
#numpy array containing only zeros.

a = np.zeros(3)
a

array([0., 0., 0.])

In [3]:
list([1,2,3,4])

[1, 2, 3, 4]

In [4]:
#we can also create numpy arrays by np.array
a = np.array([1, 2, 3, 4])         # From 2 to 4, with 5 elements
a

array([1, 2, 3, 4])

In [5]:
#To set up a grid of evenly spaced numbers use np.linspace
a = np.linspace(2, 4, 5) 
a

array([2. , 2.5, 3. , 3.5, 4. ])

In [6]:
a = np.array([[1], [2], [3], [4]])         # 2D array from a list of lists
a

array([[1],
       [2],
       [3],
       [4]])

In [7]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

(2) Shape and Dimension

In [8]:
# Consider the following assignment

z = np.zeros(10)

# Here z is a flat array with no dimension — neither row nor column vector.
# The dimension is recorded in the shape attribute, which is a tuple

z.shape

(10,)

In [9]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# To give it dimension, we can change the shape attribute
z.shape = (10, 1) #identical to z.reshape(10,1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [11]:
x[:,np.newaxis]

array([[0.33385542],
       [0.32653073],
       [0.80615494],
       ...,
       [0.59200638],
       [0.79808161],
       [0.99160529]])

In [12]:
# add a new dimension
x = np.arange(9)
print(x)
print(x[np.newaxis,:])

[0 1 2 3 4 5 6 7 8]
[[0 1 2 3 4 5 6 7 8]]


In [13]:
# This is also possible
x = np.arange(9)
print(x)
print(x[None, :],)

[0 1 2 3 4 5 6 7 8]
[[0 1 2 3 4 5 6 7 8]]


In [14]:
z = np.zeros(4)
z.shape = (2, 2)
z

array([[0., 0.],
       [0., 0.]])

In [15]:
x = np.array([[1,2],[3, 4]])   # why it has so many square bracket?
print(x.ndim, x.shape, x.size)

2 (2, 2) 4


In [16]:
x = np.array([1,2,3,4])   
print(x.ndim, x.shape, x.size)

1 (4,) 4


In [17]:
x = np.array(1)   
print(x.ndim, x.shape, x.size)

0 () 1


(3) Indexing of arrays
- negative indexing
- Array slicing : x[start:stop:step]

In [18]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
x = np.arange(10)
print(x)
print(x.ndim, x.shape, x.size)

[0 1 2 3 4 5 6 7 8 9]
1 (10,) 10


In [20]:
print(x[9])
print(x[-1])

9
9


In [21]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
x[4:7] 

array([4, 5, 6])

In [24]:
x[::2]

array([0, 2, 4, 6, 8])

In [25]:
x[2::-1]

array([2, 1, 0])

In [26]:
x[2::3]

array([2, 5, 8])

In [27]:
x = np.arange(12).reshape(3,4)

In [28]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
x[1,-1]

7

In [30]:
x[-1,-3]

9

In [31]:
x[-1] #equivalent : x[-1,:]

array([ 8,  9, 10, 11])

In [32]:
x[:,-1]

array([ 3,  7, 11])

(4) Method of arrays

In [33]:
a = np.array((4, 3, 2, 1))
a

array([4, 3, 2, 1])

In [34]:
a.sort()              # Sorts a in place
a

array([1, 2, 3, 4])

In [35]:
a.sum()   

10

In [36]:
a.mean()

2.5

In [37]:
a.max()

4

In [38]:
a.argmax()

3

In [39]:
a.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [40]:
a.cumprod()     

array([ 1,  2,  6, 24], dtype=int32)

In [41]:
a.var()   

1.25

In [42]:
a.std() 

1.118033988749895

In [43]:
a.shape = (2, 2)
a.T 

array([[1, 3],
       [2, 4]])

__Array Concatenation__: `concatenate`, `vstack`, `hstack`

In [44]:
x = np.array([[1,2,3]])
y = np.array([[3,6,9]])
np.concatenate([x,y])

array([[1, 2, 3],
       [3, 6, 9]])

In [45]:
np.r_[x,y]

array([[1, 2, 3],
       [3, 6, 9]])

In [46]:
np.concatenate([x,y], axis=1)

array([[1, 2, 3, 3, 6, 9]])

In [47]:
x = np.array([1,2,3])
y = np.array([3,6,9])
np.concatenate([x,y])
np.c_[x,y]

array([[1, 3],
       [2, 6],
       [3, 9]])

In [48]:
np.vstack([x,y])

array([[1, 2, 3],
       [3, 6, 9]])

In [49]:
np.hstack([x,y])

array([1, 2, 3, 3, 6, 9])

(5) Comparison Operator

In [50]:
x = np.array([1,2,3,4,5])

In [51]:
x < 3

array([ True,  True, False, False, False])

In [52]:
x > 3

array([False, False, False,  True,  True])

In [53]:
x != 3

array([ True,  True, False,  True,  True])

In [54]:
x == 3

array([False, False,  True, False, False])

In [55]:
y = np.array([5,5,5,5,5])
x < y

array([ True,  True,  True,  True, False])

Module, Package

(additional) Sub-packages (Module)

- NumPy provides some additional functionality related to scientific programming through its sub-packages. We’ve already seen how we can generate random variables using np.random

In [56]:
import numpy as np
from numpy import random as rnd

In [57]:
z = np.random.normal(size=10000)  # Generate standard normals
y = np.random.binomial(10, 0.5, size=1000)    # 1,000 draws from Bin(10, 0.5)
y.mean()

4.985

Another commonly used subpackage is np.linalg

In [58]:
A = np.array([[1, 2], [3, 4]])

np.linalg.det(A)  

-2.0000000000000004

In [59]:
np.linalg.inv(A)        

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

__Exercise__ (9/15 24:00)  <br>
1. Create len(10) integer array filled with zeros
2. Create 3x5 floating point array filled with ones
3. Create 3x5 array filled with 3.14
4. Create an array filled with a linear space starting at 0, ending at 20, stepping by 2
5. Create an array of five values evenly spaced between 0 and 1
6. Create a 3x3 array of uniformly distributed random (0, 1)
7. Create a 3x3 array of with mean 0 and standard deviation 1
8. Create a 3x3 array of random integers in the interval [0, 10]
9. Create a 3x3 identity matrix