## 1. Logical Operators

- Logical operators, when combined with flow control, allow for complex choices to be compactly expressed.

### 1.1 >, >=, <, <=, ==, !=

- The core logical operators are

<img src="./img/9.png" width="600" height="600">

- Logical operators can be used on scalars, arrays and matrices. 
- All comparisons are done element-by-element.
- Return either True or False (Boolean).

In [24]:
x =  np.arange(5)
print(x)
print(x<5)

[0 1 2 3 4]
[ True  True  True  True  True]


In [25]:
x = np.array([[1,2], [-3,-4]]) # (2,2)
print(x)
y = np.array([1,-1]) # (1,2)
print(y)
print(x>y)

[[ 1  2]
 [-3 -4]]
[ 1 -1]
[[False  True]
 [False False]]


In [23]:
import numpy as np

print(1.0 < 5.0)
print(1.0 == 5.0)
print(1.0 != 5.0)

x =  np.arange(5)
print(x<5)
x = np.array([[1,2], [-3,-4]])
y = np.array([1,-1])
print(x>y)

True
False
True
[ True  True  True  True  True]
[[False  True]
 [False False]]


### 1.2 and, or, not and xor

- Logical expressions can be combined using four logical devices,

<img src="./img/10.png" width="600" height="600">

- The keyword version (e.g. and) can only be used with scalars.
- Both the function and bitwise operators can be used with Numpy arrays.

In [31]:
print(~((1>2) & (3>4)))

-1


In [27]:
print((1>2) and (3<4))
print((1>2) or (3>4))
print(~((1>2) & (3>4)))

False
False
-1


In [3]:
x = np.arange(-2,4)
~((x>0) & (x<2))

array([ True,  True,  True, False,  True,  True])

In [4]:
x = np.arange(-2,4)
(x>0) & (x<2)

array([False, False, False,  True, False, False])

In [90]:
x = np.arange(-2,4)
(x>0) & (x<2)

array([False, False, False,  True, False, False])

### 1.3 Multiple tests (all and any)
- all returns True if all logical elements in an array is True.
- any returns if any element of an array is True.

In [6]:
any([False, False, False])

False

In [7]:
any([True, False, False])

True

In [21]:
all([False, False, False])

False

In [20]:
all([True, True, True])

True

In [35]:
x = np.array([1,2,3,4])
x <= 2

array([ True,  True, False, False])

In [36]:
x<=2

array([ True,  True, False, False])

In [94]:
any(x<=2)

True

In [37]:
x.ndim

1

In [38]:
x = np.array([[1,2,3,4]])
x <= 2

array([[ True,  True, False, False]])

In [39]:
x.ndim

2

In [97]:
x.shape

(1, 4)

In [5]:
import numpy as np

In [40]:
any(x<=2)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [41]:
(x<=2).any()

True

In [42]:
(x<=2).any()

True

In [43]:
x = np.array([[True, False]])
any(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [55]:
if 2>3:
    print('yes')
elif 3>2:
    print('yes')

### 2. Flow control, Loops

- Flow control utilizes logical variables to allow different code to be executed depending on whether certain conditions are met.
- Python use white space changes to indicate the start and end of flow control blocks, and so indentation matters.
- Best practice is to only use spaces (and not tabs) and to use 4 spaces when starting a new level of indentation.

In [53]:
if (1+3==4) & (1+2==4):
    print(4)

## 2.1 if, elif, else

<img src="./img/11.png" width="600" height="600">


In [16]:
x=5

if x<5:
    x += 1
else :
    x -= 1
x

4

In [ ]:
x += 1 
x = x+1

In [ ]:
x * 1
x = x*1

In [57]:
x=5

if x<5:
    x += 1
elif x>5:
    x -= 1
else :
    x *= 2
x

4

In [59]:
x=3
if x<5:
    if x<3 : 
        x+=1
    else : 
        x-=1
x

2

### 2.2 for

- for loops begin with for _item_ in _iterable_
- The generic structure of a for loop is

for _item_ in _iterable_ : 
    _Code to run_

In [61]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [60]:
count = 0
for i in range(10):
    count += i
count

45

In [64]:
np.linspace(0,500,51)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.,
       110., 120., 130., 140., 150., 160., 170., 180., 190., 200., 210.,
       220., 230., 240., 250., 260., 270., 280., 290., 300., 310., 320.,
       330., 340., 350., 360., 370., 380., 390., 400., 410., 420., 430.,
       440., 450., 460., 470., 480., 490., 500.])

In [65]:
count = 0
for i in np.linspace(0,500,51):
    count += i
count

12750.0

- Loops can also be nested

In [20]:
count = 0

for i in range(10) :
    for j in range(10) :
        count += j
        
count

450

- or can contain flow control variables

In [21]:
returns = np.random.rand(100)
count = 0
for ret in returns :
    if ret < 0 :
        count += 1
count

0

### 2.3 while

- while loops are useful when the number of iterations needed depends on the outcome of the loop contents.
- while loops are commonly used when a loop should only stop if a certain condition is met.

In [22]:
count = 0
i=0
while i < 10 :
    count += i   
    i += 1
count

45

- while loops should generally be avoided when for loops are sufficient. 
- However, there are situations where no for loop equivalence exists.

In [23]:
mu = abs(100 * np.random.rand(1))
index = 1

while abs(mu) > 0.0001 :
    mu = (mu+np.random.randn(1))/index
    index = index+1

### 2.4 break, continue

- A loop can be terminated early using break.
- continue can be used to skip an iteration of a loop

In [67]:
x = np.random.randn(1000)
for i in x :
    print(i)
    if i > 2 :
        break

0.5608117711038257
-0.4096276122046291
0.29893147598548886
1.1580203827237103
-1.1618704670923814
-1.8940675259250501
0.24932862011731818
1.0893316146166716
-1.0308629447944193
1.7176122582645554
0.6803897901909849
-0.030573759526744255
-0.13528519141922932
-0.36340337155575814
-1.625216661291272
0.7486277240213967
1.6509551249656973
1.2495701233560603
-0.988727713808935
1.0463222375689802
0.5209907482301155
0.5419462008362674
-0.4227045761507141
1.673920875021131
0.6125140613503696
1.0423982734018566
0.8168326050452839
0.690863352860169
1.0965334181445763
-0.5795698709900375
-0.1829973153761676
1.282261984715511
1.2324959181739066
-0.29918078951026944
-0.18110463406313662
-0.12381132558855015
0.7050007243502506
0.5086096045811428
-0.6892829562364172
2.146798446613535


In [4]:
import numpy as np
x = np.arange(15)
for i in x:
    if i < 10 : 
        print(i)

0
1
2
3
4
5
6
7
8
9


In [69]:
x = np.arange(15)
for i in x:
    if i < 10 : 
        continue
        print(i)
    print(i)

10
11
12
13
14


### 2.5 try, except

- try, except handles exceptions which are outside of the programmer's control. 
- In most numerical applications, code should be deterministicand so dangerous codes can usually be avoided. 
- When it can't (e.g. reading data from a data source which isn't always available), then try, except can be used.

In [27]:
text = ['a', '1', '54.1', '43.a']
for t in text :
    try :
        temp = float(t)
        print(temp)
    except ValueError:
        print('Not convertable to a float')

Not convertable to a float
1.0
54.1
Not convertable to a float


### 2.6 List Comprehensions

- List comprehensions are an optimized method of building a list which may simplify code when an iterable object is looped across and the results are saved to a list.

In [72]:
x = np.arange(5)
y = []

for i in range(5) : 
    y.append(np.exp(x[i]))
    
y

[1.0,
 2.718281828459045,
 7.38905609893065,
 20.085536923187668,
 54.598150033144236]

### Example

In [98]:
ret = [1, 2, 3, 4, 5, 6, 7]
dates = ['a', 'b', 'c', 'd', 'e', 'f', 'g']

res = []
for i, x in enumerate(ret):
    if x<=3 :
        res.append(dates[i])
res

['a', 'b', 'c']

In [103]:
[dates[i] for i, x in enumerate(ret) if x<=3]

['a', 'b', 'c']

## 3. Functions

- Functions are declared using the def keyword, and the value is returned using the return keyword.
- Consider a simple function which returns the square of the input, $y=x^2$.

In [35]:
def square(x) :
    a = x**2
    return a

# call the function
x = 2
square(x)

4

- More complex function can be crafted with multiple inputs.

In [37]:
def distance(x,y):
    return (x-y)**2

x = 3
y = 10
distance(x,y)

49

- When multiple outputs are returned but only a single variable is available for assignment, all outputs are returned in a tuple.
- The outputs can be directly assigned when the function is called with the same number of variables as outputs.

In [41]:
import numpy as np 

def get_info(x) :
    return x.ndim, x.shape, x.size

x = np.arange(100)

z = get_info(x)
print(z, type(z))

x1,x2,x3 = get_info(x)
print(x1)
print(x2)
print(x3)

(1, (100,), 100) <class 'tuple'>
1
(100,)
100


### 3.1 Keyword Arguments

- All input variables in functions are automatically keyword arguments.
- The function can be accessed either 
    - by placing inputs in the order they appear in the function, or
    - by calling the input by their name using _keyword=value_.

In [44]:
import numpy as np
def lp_norm(x,y,p):
    d = x - y
    return sum(abs(d)**p)**(1/p)

# Call the function
x = np.random.randn(10)
y = np.random.randn(10)
z1 = lp_norm(x,y,2)
z2 = lp_norm(p=2,x=x,y=y)
print(z1,z2)

5.122142181866003 5.122142181866003


### 3.2 Default Values

- Default values are set in the function declaration using _input=default_.

In [51]:
def lp_norm(x,y,p=2):
    d = x - y
    return sum(abs(d)**p)**(1/p)

# Call the function
x = np.random.randn(10)
y = np.random.randn(10)
z1 = lp_norm(x,y,2)
z2 = lp_norm(p=2,x=x,y=y)
z3 = lp_norm(x,y)
print(z1,z2,z3)

4.404410520818005 4.404410520818005 4.404410520818005


### 3.3 The Docstring

- The docstring is one of the most important elements of any function – especially a function written for use by others.
- The docstring is a special string, enclosed with triple-quotation marks, either ''' or """, which is available using help().

In [104]:
def lp_norm(x,y,p = 2):
    """ The docstring contains any available help for
    the function. A good docstring should explain the
    inputs and the outputs, provide an example and a list
    of any other related function.
    """
    d = x - y
    return sum(abs(d)**p)

In [54]:
help(lp_norm)

Help on function lp_norm in module __main__:

lp_norm(x, y, p=2)
    The docstring contains any available help for
    the function. A good docstring should explain the
    inputs and the outputs, provide an example and a list
    of any other related function.



In [ ]:
lp_norm()

In [56]:
def lp_norm(x,y,p = 2):
    """ 
    Compute the distance between vectors.
    The Lp normed distance is sum(abs(x-y)**p)**(1/p)
    
    Parameters
    ----------
    x : ndarray
    First argument
    y : ndarray
    Second argument
    p : float, optional
    Power used in distance calculation, >=0
    
    Returns
    -------
    output : scalar
    Returns the Lp normed distance between x and y
    
    Notes
    -----
    For p>=1, returns the Lp norm described above. For 0<=p<1,
    returns sum(abs(x-y)**p). If p<0, p is set to 0.
    
    Examples
    --------
    >>> x=[0,1,2]
    >>> y=[1,2,3]
    L2 norm is the default
    >>> lp_norm(x,y)
    Lp can be computed using the optional third input
    >>> lp_norm(x,y,1)
    """
    if p<0: p=0
    d = x - y
    if p == 0:
        return sum(d != 0)
    elif p < 1:
        return sum(abs(d)**p)
    else:
        return sum(abs(d)**p)**(1/p)

### 3.4 Anonymous Functions

- Python supports anonymous functions using the keyword lambda.
- Anonymous functions are usually encountered when another function expects a function as an input and a simple function will suffice.
- Anonymous function take the generic form _lambda a,b,c,... :code using a,b,c._

In [11]:
nested = [('John','Doe','Oxford'),('Jane','Dearing','Cambridge'),('Jerry','Dawn','Harvard')]
nested

[('John', 'Doe', 'Oxford'),
 ('Jane', 'Dearing', 'Cambridge'),
 ('Jerry', 'Dawn', 'Harvard')]

In [12]:
nested.sort()
nested

[('Jane', 'Dearing', 'Cambridge'),
 ('Jerry', 'Dawn', 'Harvard'),
 ('John', 'Doe', 'Oxford')]

In [19]:
def second(x): 
    return x[1]

In [20]:
second

<function __main__.second(x)>

In [21]:
nested.sort(key = second)
nested

[('Jerry', 'Dawn', 'Harvard'),
 ('Jane', 'Dearing', 'Cambridge'),
 ('John', 'Doe', 'Oxford')]